export type Language = 'en-US' | 'pt-BR';

export interface LanguageSettings {
  language: Language;
}

export interface LanguageSwitchPreference {
  rememberChoice: boolean;
  autoResetPrompts: boolean;
}

export interface Translations {
  // Navigation
  dashboard: string;
  study: string;
  history: string;
  settings: string;
  
  // Dashboard
  welcomeTitle: string;
  welcomeSubtitle: string;
  setupRequired: string;
  configureApiKey: string;
  readyToStudy: string;
  usingModel: string;
  totalSessions: string;
  completed: string;
  averageScore: string;
  startNewSession: string;
  beginNewSession: string;
  viewHistory: string;
  reviewPastSessions: string;
  recentSessions: string;
  questions: string;
  inProgress: string;
  score: string;
  
  // Study Session
  startNewStudySession: string;
  configureSession: string;
  studySubject: string;
  subjectPlaceholder: string;
  subjectModifiers: string;
  subjectModifiersPlaceholder: string;
  addModifier: string;
  removeModifier: string;
  questionType: string;
  multipleChoice: string;
  quickAssessment: string;
  dissertative: string;
  deepAnalysis: string;
  mixed: string;
  interleavedPractice: string;
  learningTechniques: string;
  makeItStickBased: string;
  spacedRepetitionDesc: string;
  interleavingDesc: string;
  elaborativeInterrogationDesc: string;
  retrievalPracticeDesc: string;
  rememberMyChoice: string;
  rememberLearningTechniques: string;
  readyToLearn: string;
  startEnhancedSession: string;
  configureApiKeyFirst: string;
  generatingQuestion: string;
  using: string;
  currentScore: string;
  question: string;
  easy: string;
  medium: string;
  hard: string;
  confidenceQuestion: string;
  notConfident: string;
  veryConfident: string;
  excellent: string;
  keepLearning: string;
  aiEvaluation: string;
  modelAnswer: string;
  elaborativePrompt: string;
  explainReasoning: string;
  selfExplanationPrompt: string;
  connectKnowledge: string;
  endSession: string;
  submitAnswer: string;
  evaluating: string;
  tryAgain: string;
  nextQuestion: string;
  pauseSession: string;
  resumeSession: string;
  
  // Session History
  studyHistory: string;
  reviewProgress: string;
  newSession: string;
  noSessionsYet: string;
  startFirstSession: string;
  allSessions: string;
  questionsAnswered: string;
  date: string;
  accuracy: string;
  continue: string;
  viewDetails: string;
  correctAnswers: string;
  deleteAllSessions: string;
  deleteAllSessionsConfirm: string;
  deleteAllSessionsWarning: string;
  sessionsDeleted: string;
  
  // Session Details
  sessionNotFound: string;
  sessionNotFoundDesc: string;
  backToHistory: string;
  sessionDetails: string;
  questionsAndAnswers: string;
  correct: string;
  yourAnswer: string;
  feedback: string;
  attempts: string;
  attempt: string;
  continueSession: string;
  
  // Settings
  settingsTitle: string;
  configurePreferences: string;
  apiConfiguration: string;
  openaiApiConfig: string;
  openaiApiKey: string;
  apiKeyStored: string;
  openaiModel: string;
  howToGetApiKey: string;
  openaiPlatform: string;
  signInOrCreate: string;
  createSecretKey: string;
  copyPasteKey: string;
  aiPrompts: string;
  aiPromptsCustomization: string;
  customizeGeneration: string;
  resetToDefaults: string;
  multipleChoicePrompt: string;
  dissertativePrompt: string;
  answerEvaluationPrompt: string;
  elaborativeInterrogationPrompt: string;
  retrievalPracticePrompt: string;
  subjectPlaceholder2: string;
  questionPlaceholder: string;
  userAnswerPlaceholder: string;
  modelAnswerPlaceholder: string;
  learningTechniquesTab: string;
  learningTechniquesSettings: string;
  manageLearningTechniques: string;
  defaultLearningTechniques: string;
  rememberChoiceForSessions: string;
  rememberChoiceDescription: string;
  unsetRememberChoice: string;
  makeItStickScience: string;
  spacedRepetition: string;
  spacedRepetitionFull: string;
  spacedRepetitionHow: string;
  interleaving: string;
  interleavingFull: string;
  interleavingHow: string;
  elaborativeInterrogation: string;
  elaborativeInterrogationFull: string;
  elaborativeInterrogationHow: string;
  selfExplanation: string;
  selfExplanationFull: string;
  selfExplanationHow: string;
  desirableDifficulties: string;
  desirableDifficultiesFull: string;
  desirableDifficultiesHow: string;
  retrievalPractice: string;
  retrievalPracticeFull: string;
  retrievalPracticeHow: string;
  generationEffect: string;
  researchBasedBenefits: string;
  improvedRetention: string;
  betterTransfer: string;
  deeperUnderstanding: string;
  metacognitiveAwareness: string;
  language: string;
  selectLanguage: string;
  about: string;
  aboutStudorama: string;
  aiPoweredPlatform: string;
  createdBy: string;
  studoramaDescription: string;
  github: string;
  linkedin: string;
  coreFeatures: string;
  aiGeneratedQuestions: string;
  mixedQuestionTypes: string;
  spacedRepetitionScheduling: string;
  elaborativePrompts: string;
  selfExplanationExercises: string;
  confidenceTracking: string;
  sessionHistoryAnalytics: string;
  learningScience: string;
  makeItStickResearch: string;
  retrievalPracticeImplementation: string;
  desirableDifficultiesIntegration: string;
  generationEffectUtilization: string;
  metacognitiveStrategyTraining: string;
  evidenceBasedSpacing: string;
  cognitiveLoadOptimization: string;
  privacySecurity: string;
  privacyDescription: string;
  scientificFoundation: string;
  scientificDescription: string;
  openSourceProject: string;
  openSourceDescription: string;
  viewOnGitHub: string;
  contributeToProject: string;
  reportIssue: string;
  requestFeature: string;
  saveSettings: string;
  saved: string;
  configurationStatus: string;
  configured: string;
  notConfigured: string;
  selectedModel: string;
  enhancedStudyMode: string;
  ready: string;
  requiresApiKey: string;
  
  // Data Management
  dataManagement: string;
  manageYourData: string;
  deleteAllData: string;
  deleteAllDataConfirm: string;
  deleteAllDataWarning: string;
  allDataDeleted: string;
  deleteAllDataDesc: string;
  
  // Language Switch Modal
  languageChange: string;
  resetPromptsOption: string;
  resetPromptsDescription: string;
  rememberChoice: string;
  confirmChange: string;
  cancel: string;
  languageSwitchPreferences: string;
  manageLanguagePreferences: string;
  resetLanguagePreferences: string;
  languagePreferencesReset: string;
  
  // OpenAI Models
  gpt4oRecommended: string;
  gpt4oMini: string;
  gpt4Turbo: string;
  gpt4: string;
  gpt35Turbo: string;
  latestMostCapable: string;
  fasterCostEffective: string;
  highPerformance: string;
  previousGeneration: string;
  fastEconomical: string;
  
  // Pricing
  supportStudorama: string;
  supportStudoramaDesc: string;
  freeForever: string;
  freeForeverDesc: string;
  noAccountRequired: string;
  startLearningImmediately: string;
  noAccountRequiredDesc: string;
  monthlySponsorship: string;
  supportFreeEducation: string;
  helpImprovePlatform: string;
  recognitionAsSupporter: string;
  helpKeepPlatformAccountless: string;
  becomeSupporter: string;
  externalCheckout: string;
  accountOptional: string;
  whySponsorStudorama: string;
  keepItFree: string;
  keepItFreeDesc: string;
  fundDevelopment: string;
  fundDevelopmentDesc: string;
  serverCosts: string;
  serverCostsDesc: string;
  privacyFirst: string;
  privacyFirstDesc: string;
  startLearningInstantly: string;
  noBarriersToLearning: string;
  noEmailRequired: string;
  noPasswordToRemember: string;
  noVerificationSteps: string;
  noPersonalDataCollection: string;
  startStudyingInSeconds: string;
  privacyFocused: string;
  dataStaysInBrowser: string;
  noTrackingOrAnalytics: string;
  yourApiKeyStaysLocal: string;
  completeAnonymity: string;
  gdprCompliantByDesign: string;
  transparencyTrust: string;
  transparencyTrustDesc: string;
  mostPopular: string;
  advanced: string;
  standard: string;
  basic: string;
  advancedDesc: string;
  standardDesc: string;
  basicDesc: string;
  
  // Theme Support
  theme: string;
  themes: string;
  appearance: string;
  selectTheme: string;
  themeSettings: string;
  customizeAppearance: string;
  
  // API Key Notifications
  apiKeyConfigured: string;
  apiKeyConfiguredDesc: string;
  invalidApiKey: string;
  invalidApiKeyDesc: string;
  apiKeyFromUrl: string;
  apiKeyPreserved: string;
  
  // Version Control
  appUpdated: string;
  versionUpdated: string;
  dataRefreshed: string;
  initializingApp: string;
  checkingUpdates: string;
  
  // Common
  loading: string;
  error: string;
  retry: string;
  delete: string;
  edit: string;
  close: string;
  yes: string;
  no: string;
  save: string;
}